### ISSUE TITLE
Proposal for adding Project Eden format

### ISSUE THREAD

**Issue by felinis** [hogsy/formats#1]
Hi hogsy, I noticed you have a Core Design section here, and for the sake of completeness I thought about adding file formats for Project Eden [that I reverse-engineered](https://github.com/felinis/RoomEditImproved/tree/main/roomedit/world) a while ago.

It's a lot more complex than other Core Design games. Let me know if you are interested in this contribution.

Best regards,
Alan

**Comment by hogsy** [comment]
Hi there!

Yeah, I'm very interested. Really cool work there :+1: 

The repository is open for contributions, so feel free to open a pull request.

I'll sort out a contributor list afterwards too.

**Comment by felinis** [comment]
Great, thanks!
